### PR TITLE
913 - Bug Fix: Edit button in sidebar does not work

### LINKED ISSUE #913: Edit button in sidebar does not work

### PR DESCRIPTION
**Pull request by shirleywbi**
## Changes
* ~~Replace edit-node emit with router update in TapestrySidebar component~~
* Capture vue edit-node and open-node events in TapestryApp
* Update jest one-node with a different description and license
## Issue Linkage
Closes #913
## PR Dependency
Depends on: N/A
Conflicts with: #864 which fixes the edit button in sidebar.
## Automated Testing
* Check sidebar renders lightbox and modal upon clicking view and edit

### CODE REVIEW

File: templates/vue/src/components/TapestrySidebar.vue [hunk 1]
```diff
@@ -179,6 +187,13 @@ export default {
         query: this.$route.query,
       })
     },
+    editNode() {
```
Comment (rlnsy) [inline templates/vue/src/components/TapestrySidebar.vue:190]: Forgive my lack of knowledge here but is there a reason we have to create a new route? I'm wondering if there's any way to use the existing edit route logic.

File: templates/vue/src/components/TapestrySidebar.vue [hunk 2]
```diff
@@ -28,11 +32,15 @@
       <header class="sidebar-header">
         <h1 ref="info" data-name="info" class="content-title">{{ node.title }}</h1>
         <div class="button-container">
-          <b-button v-if="node.accessible || canEdit" @click="viewNode">
+          <b-button
```
Comment (rlnsy) [inline templates/vue/src/components/TapestrySidebar.vue:35]: Same thing here. Is there anyway to combine this with the conditions in the regular edit button?

**Review by rlnsy — COMMENTED** [review]
@shirleywbi Works great! Just see me comments below.

File: templates/vue/src/components/TapestrySidebar.vue (hunk 1 above)
Comment (shirleywbi) [reply templates/vue/src/components/TapestrySidebar.vue:190]: I'll take a look. I think we might be able to use mixins to avoid duplicating the call in TapestryNode or add something along the lines of this when mounting TapestryNode:
```
      this.$root.$on("edit-node", id => {
        this.$router.push({
          name: names.MODAL,
          params: { nodeId: id, type: "edit", tab: "content" },
          query: this.$route.query,
        })
      })
```

Comment (shirleywbi) [reply templates/vue/src/components/TapestrySidebar.vue]: @rlnsy Thoughts on the update?

**Comment by rlnsy** [comment]
@shirleywbi I like the changes! This looks good to me.

**Review by wynnset — APPROVED** [review]
