### PR TITLE
633 - Bug fix: Video thumbnail duration showing decimals

### LINKED ISSUE #633: (Kaltura) Video duration shows many decimal places
Summary:
Video duration shows many decimal places 

Tapestry URL:
https://ubc.tapestry-tool.com/psyc101/tapestry/psyc101-98a-2020s/#/

Steps to reproduce:
Add a Kaltura video node.

Expected behaviour:
No decimal places

Actual behaviour:
Showed decimal places

Environment:
Chrome OSX

Additional information:

Name:
Steven Barnes

Email address:
sjb@psych.ubc.ca

———————————————
This task was submitted through Tapestry Bug Report
https://form.asana.com/?hash=1a1dc24c252a4098ca1084aae8d7e83470e44014581c5b9597e071ff6a3e3fa0&id=1145646772307721

### PR DESCRIPTION
**Pull request by seanRong**
Closes #633

Small change to tapestry.js to floor seconds value to remove decimal places that would otherwise occur.

### CODE REVIEW

File: templates/tapestry.js [hunk 1]
```diff
@@ -282,24 +276,14 @@ function tapestryTool(config){
...
         setNodeTypes(root);
         setLinkTypes(root);
         addDepthToNodes(root, 0, []);
 
-        // add in the controls
         if (!isReload) {
-            document.getElementById(TAPESTRY_CONTAINER_ID).prepend(tapestry.getControls());
+            svg = createSvgContainer(TAPESTRY_CONTAINER_ID);
         }
-
```
Comment (narendrasss) [inline templates/tapestry.js:302]: Were these changes intentional? They don't look related to the code.

Comment (seanRong) [reply templates/tapestry.js]: I've re-aligned it with current master
