### PR TITLE
870- Urgent fix: Unable to add root node

### LINKED ISSUE #870: Urgent fix: Unable to add root node

### PR DESCRIPTION
**Pull request by seanRong**
# Changes
Made a null check in the helper for hasPermission. The only time I believe the passed in node parameter would be null is when creating the root node, and a check for status on a null node will not work. This allows the root node to be created
## Issue Linkage
Closes #870

### CODE REVIEW

File: templates/vue/src/utils/Helpers.js [hunk 1]
```diff
@@ -140,17 +140,19 @@ export default class Helpers {
   }
 
   static hasPermission(node, action) {
-    if (node.status === "draft") {
-      if (wp.canEditTapestry() && node.reviewStatus === "submitted") {
-        return true
-      } else if (node.author && wp.isCurrentUser(node.author.id)) {
-        // authors cannot edit their submitted draft nodes
-        if (action == "edit" && node.reviewStatus === "submitted") {
+    if (node !== null) {
```
Comment (wynnset) [inline templates/vue/src/utils/Helpers.js:143]: I suggest to revert your changes and _instead_, add something here like
```
if (node === null) {
  return wp.canEditTapestry()
}
```

Comment (wynnset) [inline templates/vue/src/utils/Helpers.js:143]: I suggest to revert your changes and _instead_, add something here like
```
if (node === null) {
  return wp.canEditTapestry()
}

```

**Review by wynnset — CHANGES_REQUESTED** [review]
This fix works, but I don't like the code change because it's considering that if `hasPermission` is called, that the user `canEditTapestry`. Although this is true as of now, it would be better to code in a way that would prevent possible future changes. For example, a bit further down that function (second check), we are referring to the author of the node, which would error out if the code ever gets executed there with the `node` being `null`.

**Review by wynnset — APPROVED** [review]
